### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by erolg** [layeh/gumble#22]
Hi, I try to work barnard (but w/o uiterm package). When I call the VoiceToggle function. I got this exception. Do you have any idea why it occurs?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x14 pc=0x1dd36c]

goroutine 1 [running]:
panic(0x366000, 0x56c5e038)
	/usr/local/go/src/runtime/panic.go:481 +0x330
github.com/layeh/gumble/gumbleopenal.(*Stream).StopSource(0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/layeh/gumble/gumbleopenal/gumble_openal.go:71 +0x20
_/home/pi/loli.(*Barnard).VoiceToggle(0x56cc2c40)
	/home/pi/loli/client.go:99 +0x30
_/home/pi/loli.(*Barnard).Initialize(0x56cc2c40)
	/home/pi/loli/init.go:45 +0x1b8
_/home/pi/loli.(*Barnard).Run(0x56cc2c40)
	/home/pi/loli/init.go:11 +0x1c
main.main()
	/home/pi/loli/cmd/barnard/main.go:57 +0x5e8
exit status 2

```

**Comment by bontibon** [comment]
The error message indicates that `Barnard.Stream` is nil (i.e. hasn't been initialized with `gumbleopenal.New(b.Client)`. You can see this happening here: https://github.com/layeh/barnard/blob/master/client.go#L28

Ensure that you correct create the gumbleopenal stream.

**Comment by erolg** [comment]
Ah okay, I tried to call VoiceToggle before gumble.start(). Sorry for that.

Then I fix it. I came across with another exception. I think it is more complicating then the previous one. 

````go
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x8 pc=0x76e11778]

runtime stack:
runtime.throw(0x40bf48, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x78
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x44

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x2fa030, 0x56c2f6a8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11c fp=0x56c2f67c sp=0x56c2f664
github.com/timshannon/go-openal/openal._Cfunc_alcCaptureSamples(0x0, 0x56d6e000, 0x1e0)
	github.com/timshannon/go-openal/openal/_obj/_cgo_gotypes.go:465 +0x34 fp=0x56c2f6a4 sp=0x56c2f67c
github.com/timshannon/go-openal/openal.(*CaptureDevice).CaptureTo(0x56c18548, 0x56d6e000, 0x3c0, 0x3c0)
	/home/pi/go/src/github.com/timshannon/go-openal/openal/alcCore.go:172 +0x188 fp=0x56c2f6f0 sp=0x56c2f6a4
github.com/timshannon/go-openal/openal.(*CaptureDevice).CaptureSamples(0x56c18548, 0x1e0, 0x56d6e000, 0x3c0, 0x3c0)
	/home/pi/go/src/github.com/timshannon/go-openal/openal/alcCore.go:197 +0x8c fp=0x56c2f714 sp=0x56c2f6f0
github.com/layeh/gumble/gumbleopenal.(*Stream).sourceRoutine(0x56d29620)
	/home/pi/go/src/github.com/layeh/gumble/gumbleopenal/gumble_openal.go:132 +0x238 fp=0x56c2f7d4 sp=0x56c2f714
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:990 +0x4 fp=0x56c2f7d4 sp=0x56c2f7d4
created by github.com/layeh/gumble/gumbleopenal.(*Stream).StartSource
	/home/pi/go/src/github.com/layeh/gumble/gumbleopenal/gumble_openal.go:66 +0xb4

goroutine 1 [sleep]:
time.Sleep(0x1dcd6500, 0x0)
	/usr/local/go/src/runtime/time.go:59 +0x104
_/home/pi/loli.(*Barnard).Run(0x56c7cc40)
	/home/pi/loli/init.go:15 +0xdc
main.main()
	/home/pi/loli/cmd/barnard/main.go:57 +0x5e8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:990 +0x4

goroutine 20 [IO wait]:
net.runtime_pollWait(0x45247658, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x56c24078, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x56c24078, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).accept(0x56c24040, 0x0, 0x4627e070, 0x56c1e0e0)
	/usr/local/go/src/net/fd_unix.go:426 +0x21c
net.(*TCPListener).AcceptTCP(0x56c18050, 0x1, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4c
net/http.tcpKeepAliveListener.Accept(0x56c18050, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x3c
net/http.(*Server).Serve(0x56ce6000, 0x4627e050, 0x56c18050, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0xfc
net/http.(*Server).ListenAndServe(0x56ce6000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x124
net/http.ListenAndServe(0x3aaf10, 0x5, 0x4627e018, 0x56cdcf40, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x90
github.com/codegangsta/negroni.(*Negroni).Run(0x56cdcf40, 0x3aaf10, 0x5)
	/home/pi/go/src/github.com/codegangsta/negroni/negroni.go:102 +0x214
created by main.main
	/home/pi/loli/cmd/barnard/main.go:56 +0x5dc

goroutine 3 [IO wait]:
net.runtime_pollWait(0x452476d0, 0x72, 0x56cf0400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x56cd5bf8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x56cd5bf8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x56cd5bc0, 0x56cf0400, 0x400, 0x400, 0x0, 0x4523e0a8, 0x56c78004)
	/usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x56c18068, 0x56cf0400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x56c1c3e0, 0x4627e088, 0x56c18068, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xc8
crypto/tls.(*Conn).readRecord(0x56cea000, 0x444a17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x240
crypto/tls.(*Conn).Read(0x56cea000, 0x56d360b0, 0x6, 0x6, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x13c
io.ReadAtLeast(0x45247748, 0x56cea000, 0x56d360b0, 0x6, 0x6, 0x6, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xdc
io.ReadFull(0x45247748, 0x56cea000, 0x56d360b0, 0x6, 0x6, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x5c
github.com/layeh/gumble/gumble.(*Conn).ReadPacket(0x56d27350, 0x56d32780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/layeh/gumble/gumble/conn.go:46 +0x250
github.com/layeh/gumble/gumble.(*Client).readRoutine(0x56d1acb0)
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:220 +0x68
created by github.com/layeh/gumble/gumble.DialWithDialer
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:113 +0x370

goroutine 4 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0x56d1acb0)
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:202 +0x270
created by github.com/layeh/gumble/gumble.DialWithDialer
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:114 +0x38c

goroutine 6 [chan receive]:
github.com/layeh/gumble/gumble.(*Client).AudioOutgoing.func1(0x56d48d40, 0x56d1acb0)
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:178 +0x4c
created by github.com/layeh/gumble/gumble.(*Client).AudioOutgoing
	/home/pi/go/src/github.com/layeh/gumble/gumble/client.go:187 +0x58
exit status 2
```

Here is my code, I'm also using raspberry gpio with pushbutton and switch to trigger VoiceToggle() (IsSwitchOn and IsPushed methods.)

This exception occurs when I use this buttons several times

```go
func (b *Barnard) Run() {
        b.Initialize()
        for {
                if b.IsSwitchOn() {
                        b.Pushed = true
                        time.Sleep(time.Millisecond*500)
                } else {
                        if b.IsPushed() {
                                b.Pushed = true
                        } else {
                                b.Pushed = false
                        }
                }
                if b.LastState != b.Pushed {
                        b.VoiceToggle()
                }
        }

        b.End()
}

func (b *Barnard) Initialize() {
        if err := rpio.Open(); err != nil {
                fmt.Println(err)
                fmt.Println("Error when open the gpio pins")
                os.Exit(1)
        }

        b.LedPin.Output()
        b.PushPin.Input()
        b.SwitchPin.Input()

        b.LastState = false
        b.Pushed = false

        //Added return error to client start.
        if err := b.start(); err != nil {
                fmt.Println("Error when starting client")
                os.Exit(1)
        } else {
                b.LedPin.High()
                b.VoiceToggle()
        }

}
```
